# Generated by Django 3.2.9 on 2021-11-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('lead', models.TextField(max_length=2500)),
            ],
        ),
    ]
