# Generated by Django 3.2.9 on 2021-11-23 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_rename_post_id_postbody_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=140)),
                ('lead_paragraph', models.TextField(max_length=1000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog Article',
                'verbose_name_plural': 'Blog Articles',
                'db_table': 'articles',
            },
        ),
        migrations.CreateModel(
            name='ArticleParagraph',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('paragraph', models.TextField(max_length=1000)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
            ],
            options={
                'verbose_name': 'Article Paragraph',
                'verbose_name_plural': 'Articles Paragraphs',
                'db_table': 'article_paragraphs',
            },
        ),
        migrations.CreateModel(
            name='ParagraphType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('paragraph_type', models.CharField(max_length=50)),
                ('paragraph', models.ManyToManyField(blank=True, to='blog.ArticleParagraph')),
            ],
            options={
                'verbose_name': 'Paragraph Type',
                'verbose_name_plural': 'Paragraph Types',
                'db_table': 'paragraph_types',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('article', models.ManyToManyField(blank=True, to='blog.Article')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'tags',
            },
        ),
        migrations.RemoveField(
            model_name='postbody',
            name='post',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostBody',
        ),
    ]
